/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.interacao;

import poo.tipo.*;
import poo.exceptions.*;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author caioe_000
 */
public class EditFrame extends javax.swing.JFrame {
    //Minhas variaveis
	private Empregado emp;
    private Engenheiro eng;
    private Ensino ens;
    private Legal leg;
    private Rh rh;
    private SemSuperior sp;
    private Tecnico tec;
    private ListaFrame listaFrame; //Para copiar, modificar e retornar a lista de alunos.
    
    
    public EditFrame(ListaFrame listaFrame, int index) {
    	this.listaFrame = listaFrame;
    	this.emp = listaFrame.getLista().get(index);
    	initComponents();
        
    }
    
    public EditFrame(Engenheiro emp) {
    	this.emp = emp;
    	this.eng = emp;
    	initComponents();
        
    }
    
    public EditFrame(Ensino emp) {
    	this.emp = emp;
    	this.ens = emp;
    	initComponents();
        
    }
    
    public EditFrame(Legal emp) {
    	this.emp = emp;
    	this.leg = emp;
    	initComponents();
        
    }
    
    public EditFrame(Rh emp) {
    	this.emp = emp;
    	this.rh = emp;
    	initComponents();
        
    }
    
    public EditFrame(SemSuperior emp) {
    	this.emp = emp;
    	this.sp = emp;
    	initComponents();
        
    }
    
    public EditFrame(Tecnico emp) {
    	this.emp = emp;
    	this.tec = emp;
    	initComponents();
        
    }
           
    public int dataMesParaNumero(String str){
        int r;
        switch(str){
            case "Janeiro":
                r = 1;
                break;
            case "Fevereiro":
                r = 2;
                break;
            case "Marco":
                r = 3;
                break;
            case "Abril":
                r = 4;
                break;
            case "Maio":
                r = 5;
                break;
            case "Junho":
                r = 6;
                break;
            case "Julho":
                r = 7;
                break;
            case "Agosto":
                r = 8;
                break;
            case "Setembro":
                r = 9;
                break;
            case "Outubro":
                r = 10;
                break;
            case "Novembro":
                r = 11;
                break;
            case "Dezembro":
                r = 12;
            default:
                throw new DataException("Erro ao computar data");
        }
        
        return r;
    }
    
    public String dataNumeroParaMes(int i){
        String r;
        switch(i){
            case 1:
                r = "Janeiro";
                break;
            case 2:
                r = "Fevereiro";
                break;
            case 3:
                r = "Marco";
                break;
            case 4:
                r = "Abril";
                break;
            case 5:
                r = "Maio";
                break;
            case 6:
                r = "Junho";
                break;
            case 7:
                r = "Julho";
                break;
            case 8:
                r = "Agosto";
                break;
            case 9:
                r = "Setembro";
                break;
            case 10:
                r = "Outubro";
                break;
            case 11:
                r = "Novembro";
                break;
            case 12:
                r = "Dezembro";
            default:
                throw new DataException("Erro ao computar data");
        }
        
        return r;
    } 
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        labelNome = new javax.swing.JLabel();
        labelSalario = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        fieldNome = new javax.swing.JTextField();
        fieldSalario = new javax.swing.JTextField();
        fieldEmail = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JToggleButton();
        labelCpf = new javax.swing.JLabel();
        fieldCpf = new javax.swing.JTextField();
        labelEmail1 = new javax.swing.JLabel();
        boxDia = new javax.swing.JComboBox();
        boxMes = new javax.swing.JComboBox();
        fieldAno = new javax.swing.JTextField();
        fieldCampo = new javax.swing.JTextField();
        labelCampo = new javax.swing.JLabel();
        btnLimparCampos = new javax.swing.JButton();
        labelAumento = new javax.swing.JLabel();
        fieldAumento = new javax.swing.JTextField();
        labelAumentoPorc = new javax.swing.JLabel();
        fieldAumentoPorc = new javax.swing.JTextField();
        btnOk2 = new javax.swing.JButton();
        btnOk1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        

        
      
        labelNome.setText("Nome");

        labelSalario.setText("Salario");

        labelEmail.setText("Email");

        fieldNome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        fieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNomeActionPerformed(evt);
            }
        });

        fieldSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSalarioActionPerformed(evt);
            }
        });

        fieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEmailActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        labelCpf.setText("CPF");

        fieldCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCpfActionPerformed(evt);
            }
        });

        labelEmail1.setText("Data de admissão");

        boxDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        boxDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxDiaActionPerformed(evt);
            }
        });

        boxMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Marco", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

        fieldAno.setToolTipText("AAAA");
        fieldAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAnoActionPerformed(evt);
            }
        });

        fieldCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLicensaActionPerformed(evt);
            }
        });
        
        

        

        btnLimparCampos.setText("Limpar campos");
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });

        labelAumento.setText("Aumento salario");
        
        btnOk1.addActionListener(new ActionListener(){
        	@Override
        	public void actionPerformed(ActionEvent evt){
        		btnOk1ActionPerformed(evt);
        	}
        });
        
        btnOk2.addActionListener(new ActionListener(){
        	@Override
        	public void actionPerformed(ActionEvent evt){
        		btnOk2ActionPerformed(evt);
        	}
        });
        
        this.fieldNome.setText(this.emp.getNome());
        this.fieldSalario.setText(Double.toString(this.emp.getSalario()));
        this.fieldCpf.setText(this.emp.getCpf());
        this.fieldEmail.setText(this.emp.getEmail());
        //Setar labelCampo de acordo com o tipo
        if(this.emp instanceof Engenheiro){ 			
        	eng = (Engenheiro) emp;
        	labelCampo.setText("Area");
        	fieldCampo.setText(this.eng.getEng());
        	
		}else if(this.emp instanceof Ensino){
			ens = (Ensino) emp;
			labelCampo.setText("Formacao");
			fieldCampo.setText(this.ens.getFormacao());
			
		}else if(this.emp instanceof Legal){
			leg = (Legal) leg;
			labelCampo.setText("Cargo");
			fieldCampo.setText(this.leg.getCargo());
			
		}else if(this.emp instanceof Rh){
			rh = (Rh) emp;
			labelCampo.setText("Funcao");
			fieldCampo.setText(this.rh.getFuncao());
		}else if(this.emp instanceof SemSuperior){
			sp = (SemSuperior) emp;
			labelCampo.setText("Funcao");
			fieldCampo.setText(this.sp.getFuncao());
		}else if(this.emp instanceof Tecnico){	
			tec = (Tecnico) emp;
			labelCampo.setText("Licensa");
			fieldCampo.setText(this.tec.getLicensa());
		}
        
        this.fieldAno.setText(Integer.toString(this.emp.getDataAdm().get(0)));
        
        this.boxMes.setSelectedIndex(this.emp.getDataAdm().get(1));
        this.boxDia.setSelectedIndex(this.emp.getDataAdm().get(2));

    
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNome)
                            .addComponent(labelSalario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldSalario)
                            .addComponent(fieldNome, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCampo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(labelEmail1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLimparCampos)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalvar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAumentoPorc)
                                    .addComponent(labelAumento))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldAumento)
                                    .addComponent(fieldAumentoPorc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnOk2)
                                    .addComponent(btnOk1, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(6, 6, 6))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSalario)
                    .addComponent(fieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCpf)
                    .addComponent(fieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEmail)
                    .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCampo)
                    .addComponent(fieldCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail1)
                    .addComponent(labelAumento)
                    .addComponent(fieldAumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOk1))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAumentoPorc)
                    .addComponent(fieldAumentoPorc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOk2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnLimparCampos))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>     
    
   	public void btnOk1ActionPerformed(ActionEvent evt){
		emp.aumentoLiq(Double.parseDouble(fieldAumento.getText()));
		this.fieldSalario.setText(Double.toString(this.emp.getSalario()));
		this.fieldAumento.setText("");
		this.listaFrame.atualizaLista();
	}
   	
   	public void btnOk2ActionPerformed(ActionEvent evt){
		emp.aumentoPorc(Double.parseDouble(fieldAumentoPorc.getText()));
		this.fieldSalario.setText(Double.toString(this.emp.getSalario()));
		this.fieldAumentoPorc.setText("");
		this.listaFrame.atualizaLista();
	}

    private void fieldNomeActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void fieldSalarioActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void fieldEmailActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        String nome=null, email=null, cpf=null, licensa=null; //Apenas inicializando para posterior checagem
        Double salario=null;
        ArrayList<Integer> data = new ArrayList<>();
        
        
        if(!this.fieldNome.getText().isEmpty()) nome = this.fieldNome.getText();
        else  nome = "N/A";
        
        if(!this.fieldSalario.getText().isEmpty()) 
            salario = Double.parseDouble(this.fieldSalario.getText());
        else{
            this.labelSalario.setText("<HTML><font color=black>Salario</font><font color=red>*</font></HTML>"); //Salario*, com * em vermelho
        }
        
        if(!this.fieldEmail.getText().isEmpty())  email = this.fieldEmail.getText();
        else{
            this.labelEmail.setText("<HTML><font color=black>Email</font><font color=red>*</font></HTML>"); //Email*, com * em vermelho
        }
        
        if(!this.fieldCpf.getText().isEmpty())  cpf = this.fieldCpf.getText();
        else{
            this.labelCpf.setText("<HTML><font color=black>CPF</font><font color=red>*</font></HTML>"); //CPF*, com * em vermelho
        }
        
        if(!this.fieldCampo.getText().isEmpty())  licensa = this.fieldCampo.getText();
        else{
            this.labelCampo.setText("<HTML><font color=black>Licensa</font><font color=red>*</font></HTML>"); //Funcao*, com * em vermelho
        }
        
        data.add(Integer.parseInt(this.fieldAno.getText())); //Pega o campo ano e transforma p/ int
        data.add((this.boxMes.getSelectedIndex() + 1)); // Número do mês
        data.add((this.boxDia.getSelectedIndex() +1)); //Número do dia
                   
        try{
        	this.emp.setNome(nome);
        	this.emp.setSalario(salario);
        	this.emp.setEmail(email);
        	this.emp.setCpf(cpf);
        	this.emp.setDataAdm(data.get(2), data.get(1), data.get(0));
        	
        	this.listaFrame.atualizaLista();
        	this.dispose();
        	
        } catch (SalarioException ex) {
            JOptionPane.showMessageDialog(null, 
                    ex.getMessage(),
                    "ERRO",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }                                         

    private void fieldCpfActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void boxDiaActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void fieldAnoActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void fieldLicensaActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {                                                
        this.fieldNome.setText("");
        this.fieldSalario.setText("");
        this.fieldCpf.setText("");
        this.fieldEmail.setText("");
        this.fieldCampo.setText("");
        this.fieldAno.setText("");
    }                                               

    private void fieldAumentoActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox boxDia;
    private javax.swing.JComboBox boxMes;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnOk1;
    private javax.swing.JButton btnOk2;
    private javax.swing.JToggleButton btnSalvar;
    private javax.swing.JTextField fieldAno;
    private javax.swing.JTextField fieldAumento;
    private javax.swing.JTextField fieldAumentoPorc;
    private javax.swing.JTextField fieldCpf;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldCampo;
    private javax.swing.JTextField fieldNome;
    private javax.swing.JTextField fieldSalario;
    private javax.swing.JLabel labelAumento;
    private javax.swing.JLabel labelAumentoPorc;
    private javax.swing.JLabel labelCampo;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEmail1;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSalario;
    // End of variables declaration                   

    /**
     * @return the listaFrame
     */
    public ListaFrame getListaFrame() {
        return listaFrame;
    }

    /**
     * @param listaFrame the listaFrame to set
     */
    public void setListaFrame(ListaFrame listaFrame) {
        this.listaFrame = listaFrame;
    }

}
