package poo.interacao;

import java.io.FileNotFoundException;
import java.io.IOException;

import poo.tipo.*;
import poo.interfaces.InterfaceEmpregado;

import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import poo.logica.Escritor;
import poo.logica.Leitor;
import poo.logica.Serializador;
import poo.logica.TableMouseListener;

/**
 *
 * @author caioe_000
 */
 public class ListaFrame extends javax.swing.JFrame {
    
    //Minhas variaveis
    private AddFrameEngenheiro frameEngenheiro;
    private AddFrameEnsino frameEnsino;
    private AddFrameLegal frameLegal;
    private AddFrameRH frameRh;
    private AddFrameSemSuperior frameSemSuperior;
    private AddFrameTecnico frameTecnico;
        
    private ArrayList<Empregado> lista;
    
    
    
    //FIM das minhas variáveis
    
    /**
     * Creates new form ListaFrame
     */
    public ListaFrame() {
        initComponents();
        this.lista = new ArrayList<>();
        
        try {
                if(new Serializador().abre() != null)
                    carregaLista();
		} catch (ClassNotFoundException | IOException e) {
			// TODO Auto-generated catch block
			JOptionPane.showMessageDialog(null, 
                    e.getMessage(),
                    "ERRO",
                    JOptionPane.INFORMATION_MESSAGE);
		}
        	
    }
    
    public void imprimeLista(){
        System.out.println("LISTA-------------");
        for(Empregado key : this.lista)
            System.out.println(key.getNome() + " | " + key.getCpf() + " | " + key.getEmail());
    }
    
    public void carregaLista(){
        Serializador ser = new Serializador();
        
        try {
            this.lista = (ArrayList) ser.abre();
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, 
                    "Erro ao carregar lista.",
                    "ERRO I/O",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, 
                    "Erro ao carregar - Classe nao encontrada.",
                    "ERRO I/O",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        
        atualizaLista();
    }
    
    public void salvaLista(){
        Serializador ser = new Serializador();
        try {
            ser.grava(this.lista);
            
        } catch (FileNotFoundException ex){
            JOptionPane.showMessageDialog(null, 
                    "Arquivos corrompidos.  FILE_NOT_FOUND",
                    "ERRO I/O",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, 
                    "Erro ao salvar lista.",
                    "ERRO I/O",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void passaLista(InterfaceEmpregado eng){
        this.lista.add((Empregado) eng);
    }
    
    public void atualizaLista(){ 
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        


        dtm.setRowCount(0);

        for(Empregado key : this.lista){              

            Vector row = new Vector();

            this.table.setRowSelectionAllowed(true);
            row.add(key.getNome());
            row.add(key.getSalario());
            row.add(key.getCpf());
            row.add(key.getEmail());


            dtm.addRow(row);
        }
        
        this.salvaLista();

    }
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        menuVerPerfil = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenuItem();
        menuAddAnotacao = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        itemEngenheiro = new javax.swing.JMenuItem();
        itemEnsino = new javax.swing.JMenuItem();
        itemLegal = new javax.swing.JMenuItem();
        itemRh = new javax.swing.JMenuItem();
        itemTecnico = new javax.swing.JMenuItem();
        itemSemSuperior = new javax.swing.JMenuItem();

        jPopupMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPopupMenu1MouseReleased(evt);
            }
        });

        menuVerPerfil.setText("Ver perfil");
        menuVerPerfil.setToolTipText("");
        menuVerPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVerPerfilActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuVerPerfil);

        menuEditar.setText("Editar");
        jPopupMenu1.add(menuEditar);

        menuAddAnotacao.setText("Adicionar anotacao");
        jPopupMenu1.add(menuAddAnotacao);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Salario", "CPF", "Emaill"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableMouseReleased(evt);
            }
        });
        table.setComponentPopupMenu (this.jPopupMenu1);
        jScrollPane1.setViewportView(table);

        menuFile.setText("File");
        menuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFileActionPerformed(evt);
            }
        });

        jMenu1.setText("Add");

        itemEngenheiro.setText("Engenheiro");
        itemEngenheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEngenheiroActionPerformed(evt);
            }
        });
        jMenu1.add(itemEngenheiro);

        itemEnsino.setText("Ensino");
        itemEnsino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEnsinoActionPerformed(evt);
            }
        });
        jMenu1.add(itemEnsino);

        itemLegal.setText("Setor legal");
        itemLegal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLegalActionPerformed(evt);
            }
        });
        jMenu1.add(itemLegal);

        itemRh.setText("Recursos Humanos");
        itemRh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRhActionPerformed(evt);
            }
        });
        jMenu1.add(itemRh);

        itemTecnico.setText("Tecnico");
        itemTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTecnicoActionPerformed(evt);
            }
        });
        jMenu1.add(itemTecnico);

        itemSemSuperior.setText("Sem superior");
        itemSemSuperior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSemSuperiorActionPerformed(evt);
            }
        });
        jMenu1.add(itemSemSuperior);

        menuFile.add(jMenu1);

        jMenuBar1.add(menuFile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
        );
        
        table.addMouseListener(new TableMouseListener(table));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_menuFileActionPerformed

    private void itemEngenheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEngenheiroActionPerformed
        frameEngenheiro = new AddFrameEngenheiro(this);
        frameEngenheiro.setVisible(true);
        frameEngenheiro.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_itemEngenheiroActionPerformed

    private void itemEnsinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEnsinoActionPerformed
        frameEnsino = new AddFrameEnsino(this);
        frameEnsino.setVisible(true);
        frameEnsino.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_itemEnsinoActionPerformed

    private void itemLegalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLegalActionPerformed
        frameLegal = new AddFrameLegal(this);
        frameLegal.setVisible(true);
        frameLegal.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_itemLegalActionPerformed

    private void itemRhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRhActionPerformed
        frameRh = new AddFrameRH(this);
        frameRh.setVisible(true);
        frameRh.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_itemRhActionPerformed

    private void itemTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTecnicoActionPerformed
        frameTecnico = new AddFrameTecnico(this);
        frameTecnico.setVisible(true);
        frameTecnico.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_itemTecnicoActionPerformed

    private void itemSemSuperiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSemSuperiorActionPerformed
        frameSemSuperior = new AddFrameSemSuperior(this);
        frameSemSuperior.setVisible(true);
        frameSemSuperior.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_itemSemSuperiorActionPerformed

    private void jPopupMenu1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPopupMenu1MouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPopupMenu1MouseReleased

    private void menuVerPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVerPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuVerPerfilActionPerformed

    private void tableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseReleased
        if(evt.isPopupTrigger()){
            this.jPopupMenu1.show(this, evt.getX(), evt.getY());
        }
            
        
    }//GEN-LAST:event_tableMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemEngenheiro;
    private javax.swing.JMenuItem itemEnsino;
    private javax.swing.JMenuItem itemLegal;
    private javax.swing.JMenuItem itemRh;
    private javax.swing.JMenuItem itemSemSuperior;
    private javax.swing.JMenuItem itemTecnico;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuAddAnotacao;
    private javax.swing.JMenuItem menuEditar;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuVerPerfil;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
