/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.interacao;

import poo.interfaces.InterfaceEmpregado;
import poo.tipo.*;

/**
 *
 * @author caioe_000
 */
public class PerfilGeralFrame extends javax.swing.JFrame {

    /**
     * Creates new form perfilGeral
     */
	//MINHAS VARIAVEIS
	private Engenheiro eng;
	private Ensino ens;
	private Legal leg;
	private Rh rh;
	private SemSuperior sp;
	private Tecnico tec;
	
    public PerfilGeralFrame(Engenheiro emp) {
        initComponents();
        this.eng = emp;
    }
    
    public PerfilGeralFrame(Ensino emp) {
        initComponents();
        this.ens = emp;
    }
    
    public PerfilGeralFrame(Legal emp) {
        initComponents();
        this.leg = emp;
    }
    
    public PerfilGeralFrame(Rh emp) {
        initComponents();
        this.rh = emp;
    }
    
    public PerfilGeralFrame(SemSuperior emp) {
        initComponents();
        this.sp = emp;
    }
    
    public PerfilGeralFrame(Tecnico emp) {
        initComponents();
        this.tec = emp;
    }
    
    private void campos(Empregado emp){

        labelNome.setText("Nome: " + emp.getNome());

        labelSalario.setText("Salario: " + emp.getSalario());

        labelCpf.setText("CPF: " + emp.getCpf());

        labelData.setText("Data de nascimento: " + emp.getDataAdm().get(0) + "/" + emp.getDataAdm().get(1) + "/" + emp.getDataAdm().get(2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNome = new javax.swing.JLabel();
        labelSalario = new javax.swing.JLabel();
        labelCpf = new javax.swing.JLabel();
        labelCampo = new javax.swing.JLabel();
        labelData = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fieldNote = new javax.swing.JTextArea();
        btnProx = new javax.swing.JButton();
        btnAnt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNome.setText("Nome: ");

        labelSalario.setText("Salario:");

        labelCpf.setText("CPF: ");

        labelCampo.setText("Campo:");

        labelData.setText("Data de nascimento:");

        fieldNote.setEditable(false);
        fieldNote.setColumns(20);
        fieldNote.setLineWrap(true);
        fieldNote.setRows(5);
        fieldNote.setWrapStyleWord(true);
        jScrollPane1.setViewportView(fieldNote);

        btnProx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poo/interacao/glyphicons-179-step-forward.png"))); // NOI18N

        btnAnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poo/interacao/glyphicons-171-step-backward.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNome)
                    .addComponent(labelSalario)
                    .addComponent(labelCpf)
                    .addComponent(labelCampo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAnt)
                            .addComponent(btnProx, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelData))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSalario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCpf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelData)
                .addGap(8, 8, 8)
                .addComponent(labelCampo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnProx)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAnt)
                        .addGap(42, 42, 42))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnt;
    private javax.swing.JButton btnProx;
    private javax.swing.JTextArea fieldNote;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCampo;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSalario;
    // End of variables declaration//GEN-END:variables
}
